# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package with Docker Image CI

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose automation suite: RegressionSuite, SmokeSuite'
        required: true
        default: RegressionSuite

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.42.0-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run automation suite with Playwright
        run: mvn clean install -DsuiteXmlFile=suites/${{github.event.inputs.suite}} -PCustomSuite

      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TestNG Report
          path: emailable-report.html